In [1]:
%config IPCompleter.greedy=True


In [2]:
import pandas as pd

df_train = pd.read_csv('train_kaggle.csv')
df_train

Id  Label
0          0      1
1          1      0
2          2      0
3          3      1
4          4      0
5          5      1
6          6      0
7          7      1
8          8      0
9          9      0
10        10      1
11        11      0
12        12      1
13        13      1
14        14      0
15        15      1
16        16      0
17        17      1
18        18      1
19        19      1
20        20      1
21        21      1
22        22      1
23        23      1
24        24      0
25        25      1
26        26      1
27        27      0
28        28      0
29        29      1
...      ...    ...
18632  18632      0
18633  18633      1
18634  18634      1
18635  18635      0
18636  18636      0
18637  18637      0
18638  18638      0
18639  18639      0
18640  18640      0
18641  18641      0
18642  18642      0
18643  18643      1
18644  18644      0
18645  18645      0
18646  18646      0
18647  18647      0
18648  18648      0
18649  18649      0
18650  18650      1
18651  18651      0
18652  18652      0
18653  18653      0
18654  18654      1
18655  18655      0
18656  18656      0
18657  18657      1
18658  18658      0
18659  18659      0
18660  18660      1
18661  18661      1

[18662 rows x 2 columns]

In [3]:
import seaborn as sns

sns.distplot(df_train['Label']);

In [4]:
import numpy as np

def load_dataframe(id):
    train_data = np.load("train/train/{}.npy".format(id))
    return pd.DataFrame(data=train_data)

In [29]:
def load_test_dataframe(id):
    test_data = np.load("test/test/{}.npy".format(id))
    return pd.DataFrame(data=test_data)

In [5]:
def get_missing_data(df):
    total = df.isnull().sum().sort_values(ascending=False)
    percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
    missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
    return missing_data

In [6]:
def clear_missing_data(df, missing_indices):
    df = df.drop(missing_indices,1)
    # for col in df_temp.columns:
    #    df = df.drop(df.loc[df[col].isnull()].index)
    count = df.isnull().sum().max() #just checking that there's no missing data missing...
    if count > 0:
        print(count)
        return pd.DataFrame()
    return df

In [7]:
df0 = load_dataframe(0)
df0

0    1    2    3    4    5    6    7    8    9    ...  92         93   \
0   -1.0  0.0  0.0  0.0 -2.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
1   -1.0  0.0  0.0  0.0  1.0  0.0  0.0 -1.0  1.0  0.0  ...  0.0   0.000000   
2    0.0  0.0  0.0  1.0 -1.0  0.0  1.0  0.0  1.0 -1.0  ...  0.0   0.000000   
3    0.0  1.0  0.0  0.0  0.0 -1.0  0.0  0.0  1.0  0.0  ...  0.0   0.000000   
4    0.0 -1.0  0.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  2.0  10.000000   
5    0.0  0.0  0.0  0.0  1.0  0.0 -1.0  0.0  1.0  0.0  ...  2.0  12.000000   
6   -1.0  0.0  0.0  0.0 -2.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
7    0.0  0.0  0.0  0.0 -3.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
8   -1.0  0.0  0.0  0.0 -2.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
9   -1.0  0.0  0.0  0.0 -2.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
10   0.0  0.0  1.0  0.0  0.0  0.0 -1.0 -1.0  1.0  0.0  ...  0.0   0.000000   
11  -1.0  0.0  0.0  0.0 -2.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
12  -1.0  0.0  0.0  0.0 -2.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
13  -1.0  0.0  0.0  0.0 -2.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
14  -1.0  0.0  0.0  0.0 -2.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
15  -1.0  0.0  0.0  0.0 -2.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
16  -1.0  0.0  0.0  0.0 -2.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
17  -1.0  0.0  0.0  0.0 -2.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
18   0.0  0.0  0.0  0.0 -3.0  0.0  1.0  0.0  0.0  0.0  ...  0.0   0.000000   
19   0.0 -1.0  0.0  0.0  0.0  0.0 -1.0  0.0  1.0  0.0  ...  1.0  12.000000   
20   0.0  0.0  0.0  0.0  1.0  0.0 -1.0  0.0  1.0  0.0  ...  2.0  10.000000   
21   0.0  0.0  0.0  0.0  1.0  0.0 -1.0  0.0  1.0  0.0  ...  2.0  10.500000   
22   0.0  0.0  0.0  0.0  1.0  0.0 -1.0  0.0  1.0  0.0  ...  2.0  12.500000   
23   0.0  0.0  0.0  0.0  1.0  0.0 -1.0  0.0  1.0  0.0  ...  2.0  11.000000   
24   0.0  0.0  0.0  0.0  1.0  0.0 -1.0  0.0  1.0  0.0  ...  2.0  12.000000   
25   0.0  0.0  0.0  0.0  1.0  0.0 -1.0  0.0  1.0  0.0  ...  2.0  12.000000   
26   0.0  0.0  0.0  0.0  1.0  0.0 -1.0  0.0  1.0  0.0  ...  2.0  12.000000   
27   0.0  0.0  0.0  0.0  1.0  0.0 -1.0  0.0  1.0  0.0  ...  2.0  13.000000   
28   0.0  0.0  0.0  0.0  1.0  0.0 -1.0  0.0  1.0  0.0  ...  2.0  13.000000   
29   0.0  0.0  0.0  0.0  1.0  0.0 -1.0  0.0  1.0  0.0  ...  2.0  10.000000   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...        ...   
970  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0   0.000000   
971  0.0 -1.0  0.0  0.0  0.0  0.0  1.0  1.0 -3.0 -3.0  ...  0.0   0.000000   
972  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0 -1.0  ...  4.0  88.500000   
973  0.0  0.0  0.0  0.0 -2.0  1.0 -1.0  0.0  1.0 -2.0  ...  0.0   0.000000   
974  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0   0.000000   
975  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0   0.000000   
976  0.0 -1.0  0.0  0.0  0.0  0.0  1.0  1.0 -3.0 -3.0  ...  0.0   0.000000   
977  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0 -1.0  ...  4.0  90.000000   
978  0.0  0.0  0.0  0.0 -2.0  1.0 -1.0  0.0  1.0 -2.0  ...  0.0   0.000000   
979  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0   0.000000   
980  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0   0.000000   
981  0.0 -1.0  0.0  0.0  0.0  0.0  1.0  1.0 -3.0 -3.0  ...  0.0   0.000000   
982  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0 -1.0  ...  4.0  88.500000   
983  0.0  0.0  0.0  0.0 -2.0  1.0 -1.0  0.0  1.0 -2.0  ...  0.0   0.000000   
984  0.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0   0.000000   
985  0.0  0.0  0.0  2.0  0.0  0.0  0.0  0.0  1.0  0.0  ...  0.0   0.000000   
986  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0 -1.0  ...  1.0  20.000000   
987  0.0 -1.0  0.0  0.0  0.0  0.0  1.0  1.0 -3.0 -3.0  ...  0.0   0.000000   
988  0.0  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0 -1.0  ...  4.0  88.000000   
989  0.0 -1.0  0.0  0.0  0.

In [8]:
get_missing_data(df0)

Total  Percent
101      0      0.0
37       0      0.0
27       0      0.0
28       0      0.0
29       0      0.0
30       0      0.0
31       0      0.0
32       0      0.0
33       0      0.0
34       0      0.0
35       0      0.0
36       0      0.0
38       0      0.0
25       0      0.0
39       0      0.0
40       0      0.0
41       0      0.0
42       0      0.0
43       0      0.0
44       0      0.0
45       0      0.0
46       0      0.0
47       0      0.0
48       0      0.0
26       0      0.0
24       0      0.0
100      0      0.0
11       0      0.0
1        0      0.0
2        0      0.0
..     ...      ...
96       0      0.0
97       0      0.0
98       0      0.0
99       0      0.0
77       0      0.0
76       0      0.0
75       0      0.0
74       0      0.0
53       0      0.0
54       0      0.0
55       0      0.0
56       0      0.0
57       0      0.0
58       0      0.0
59       0      0.0
60       0      0.0
61       0      0.0
62       0      0.0
63       0      0.0
64       0      0.0
65       0      0.0
66       0      0.0
67       0      0.0
68       0      0.0
69       0      0.0
70       0      0.0
71       0      0.0
72       0      0.0
73       0      0.0
0        0      0.0

[102 rows x 2 columns]

In [9]:
import tensorflow as tf


c:\users\jw.chan\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\jw.chan\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\jw.chan\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\jw.c

In [11]:
dataframes = []
for id in df_train['Id']:
    dfi = load_dataframe(id)
    dataframes.append(dfi.values)
dataframes

[array([[-1.,  0.,  0., ...,  0.,  0.,  0.],
        [-1.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [ 0.,  0.,  0., ...,  0.,  0.,  1.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0., -1.,  0., ...,  0.,  0.,  0.]], dtype=float32),
 array([[-2.,  0.,  1., ...,  0.,  0.,  0.],
        [-1.,  2.,  0., ...,  0.,  0.,  0.],
        [-1.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [-1.,  0.,  0., ...,  0.,  0.,  0.],
        [-1.,  0.,  0., ...,  0.,  0.,  0.],
        [-1.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32),
 array([[-2.,  0.,  1., ...,  0.,  0.,  0.],
        [-1.,  2.,  0., ...,  0.,  0.,  0.],
        [-1.,  0.,  0., ...,  0.,  0.,  0.],
        ...,
        [-1.,  0.,  0., ...,  0.,  0.,  0.],
        [-1.,  0.,  0., ...,  0.,  0.,  0.],
        [-1.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32),
 array([[ 0., -1.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 

In [28]:
np.save('allData.npy', np.array(dataframes))

In [85]:
def pad_data(dfs):
    data = []
    for i in range(len(dfs)):
        df = dfs[i]
        diff = 1000 - df.shape[0]
        if diff > 0:
            halfDiff = int(diff / 2)
            df = np.pad(df, [(halfDiff, halfDiff + diff % 2), (0,0)], 'constant')
        data.append(df)
    data = np.stack(data)
    return data

In [86]:
XTrain = pad_data(dataframes)
XTrain.shape

(18662, 1000, 102)

In [99]:
np.save('train_padded.npy', np.array(XTrain))

In [87]:
XTrain[0].shape

(1000, 102)

In [91]:
Y = df_train['Label']
Y.shape

(18662,)

In [94]:
from tensorflow import keras

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(1000, 102)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(2, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [62]:
df_test = pd.read_csv('sample_solution.csv')
df_test

Id  Predicted
0        0   0.417022
1        1   0.720324
2        2   0.000114
3        3   0.302333
4        4   0.146756
5        5   0.092339
6        6   0.186260
7        7   0.345561
8        8   0.396767
9        9   0.538817
10      10   0.419195
11      11   0.685220
12      12   0.204452
13      13   0.878117
14      14   0.027388
15      15   0.670468
16      16   0.417305
17      17   0.558690
18      18   0.140387
19      19   0.198101
20      20   0.800745
21      21   0.968262
22      22   0.313424
23      23   0.692323
24      24   0.876389
25      25   0.894607
26      26   0.085044
27      27   0.039055
28      28   0.169830
29      29   0.878143
...    ...        ...
6021  6021   0.303023
6022  6022   0.035078
6023  6023   0.590051
6024  6024   0.701621
6025  6025   0.669988
6026  6026   0.356210
6027  6027   0.111645
6028  6028   0.641320
6029  6029   0.063197
6030  6030   0.644363
6031  6031   0.835289
6032  6032   0.057159
6033  6033   0.355870
6034  6034   0.618719
6035  6035   0.638601
6036  6036   0.197939
6037  6037   0.623363
6038  6038   0.557541
6039  6039   0.885718
6040  6040   0.697025
6041  6041   0.364263
6042  6042   0.225348
6043  6043   0.610909
6044  6044   0.255565
6045  6045   0.075813
6046  6046   0.822702
6047  6047   0.227952
6048  6048   0.379553
6049  6049   0.846487
6050  6050   0.103151

[6051 rows x 2 columns]

In [63]:
testdatas = []
for id in df_test['Id']:
    dfi = load_test_dataframe(id)
    testdatas.append(dfi.values)

In [64]:
print(len(testdatas))

6051


In [88]:
XTest = pad_data(testdatas)

In [100]:
np.save('test_padded.npy', np.array(XTest))

In [89]:
XTest.shape

(6051, 1000, 102)

In [95]:
model.fit(XTrain, Y, epochs=5)


Epoch 1/5
18662/18662 [==============================] - 35s 2ms/sample - loss: 1.1192 - acc: 0.8456
Epoch 2/5
18662/18662 [==============================] - 35s 2ms/sample - loss: 0.3174 - acc: 0.8764
Epoch 3/5
18662/18662 [==============================] - 35s 2ms/sample - loss: 0.2817 - acc: 0.8925
Epoch 4/5
18662/18662 [==============================] - 34s 2ms/sample - loss: 0.2652 - acc: 0.8977
Epoch 5/5
18662/18662 [==============================] - 34s 2ms/sample - loss: 0.2104 - acc: 0.9076


In [96]:
YTest = model.predict(XTest)
YTest

array([[1.4133734e-04, 9.9985862e-01],
       [5.3798878e-01, 4.6201131e-01],
       [9.9998820e-01, 1.1790838e-05],
       ...,
       [9.9997485e-01, 2.5205749e-05],
       [5.9756237e-01, 4.0243763e-01],
       [9.9997199e-01, 2.7954635e-05]], dtype=float32)

In [97]:
df_test['Predicted'] = YTest[:, 0]
df_test

Id     Predicted
0        0  1.413373e-04
1        1  5.379888e-01
2        2  9.999882e-01
3        3  1.990660e-13
4        4  5.830460e-01
5        5  9.967662e-01
6        6  9.995585e-01
7        7  9.142907e-02
8        8  1.549639e-03
9        9  2.385528e-02
10      10  5.705579e-01
11      11  1.929456e-07
12      12  6.750550e-02
13      13  5.975624e-01
14      14  9.999944e-01
15      15  9.993739e-01
16      16  8.097188e-01
17      17  1.578979e-06
18      18  8.051250e-01
19      19  9.993995e-01
20      20  3.275776e-03
21      21  9.994243e-01
22      22  8.116960e-01
23      23  2.166401e-07
24      24  1.850342e-06
25      25  9.993528e-01
26      26  8.092001e-01
27      27  9.999688e-01
28      28  5.975624e-01
29      29  8.100768e-01
...    ...           ...
6021  6021  5.975624e-01
6022  6022  8.110044e-01
6023  6023  1.182025e-01
6024  6024  1.187849e-03
6025  6025  1.750357e-01
6026  6026  8.993917e-01
6027  6027  5.975624e-01
6028  6028  1.185939e-10
6029  6029  9.980437e-01
6030  6030  6.324498e-03
6031  6031  2.097679e-04
6032  6032  1.439121e-02
6033  6033  5.975624e-01
6034  6034  8.081666e-01
6035  6035  9.991456e-01
6036  6036  9.993600e-01
6037  6037  6.802446e-11
6038  6038  8.113761e-01
6039  6039  3.891908e-03
6040  6040  9.999692e-01
6041  6041  5.975624e-01
6042  6042  9.992809e-01
6043  6043  9.999973e-01
6044  6044  9.993592e-01
6045  6045  5.975624e-01
6046  6046  2.141197e-01
6047  6047  6.022514e-02
6048  6048  9.999748e-01
6049  6049  5.975624e-01
6050  6050  9.999720e-01

[6051 rows x 2 columns]

In [98]:
df_test.to_csv('test.csv', index=False)
